# Generated by Django 5.2.16 on 2026-07-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('job_title', models.CharField(max_length=255, verbose_name='عنوان شغل')),
                ('button_text', models.CharField(max_length=100, verbose_name='متن دکمه')),
                ('avatar', models.ImageField(upload_to='hero/', verbose_name='تصویر آواتار')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='hero/resume/', verbose_name='رزومه')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
