# Generated by Django 5.2.16 on 2026-07-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_herosection_delete_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان توانایی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('svg_code', models.TextField(verbose_name='SVG کد')),
            ],
            options={
                'verbose_name': 'ماژول توانایی\u200cها',
                'verbose_name_plural': 'توانایی\u200cها',
            },
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'مشخصات'},
        ),
    ]
