# Generated by Django 5.2.16 on 2026-07-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicessection_delete_services_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'ماژول اطلاعات شخصی', 'verbose_name_plural': 'اطلاعات شخصی'},
        ),
    ]
