# Generated by Django 5.2.16 on 2026-07-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_herosection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicessection',
            name='description',
            field=models.CharField(max_length=300, verbose_name='توضیحات'),
        ),
    ]
