# Generated by Django 5.2.16 on 2026-08-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_servicessection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicessection',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
