# Generated by Django 5.2.16 on 2026-08-03 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_servicessection_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='نقل قول')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('job_title', models.CharField(max_length=100, verbose_name='عنوان شغلی')),
                ('name', models.CharField(max_length=100, verbose_name='اسم')),
                ('signature', models.ImageField(upload_to='about/', verbose_name='تصویر امضا')),
                ('main_image', models.ImageField(upload_to='about/', verbose_name='عکس اصلی')),
                ('circle_text', models.CharField(default='About Me - About Me - About Me -', max_length=200, verbose_name='متن دور عکس')),
            ],
            options={
                'verbose_name': 'درباره من',
                'verbose_name_plural': 'درباره من',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مهارت')),
                ('percentage', models.PositiveIntegerField(verbose_name='درصد (۰ تا ۱۰۰)')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('bg_color', models.CharField(default='#faf1c6', max_length=20, verbose_name='رنگ پس\u200cزمینه')),
                ('circle_color', models.CharField(blank=True, help_text='مثلاً: blue, green, red (اختیاری)', max_length=20, verbose_name='رنگ دایره')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.about', verbose_name='درباره')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SkillIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.ImageField(upload_to='about/skill_icons/', verbose_name='تصویر آیکون')),
                ('icon_dark', models.ImageField(blank=True, null=True, upload_to='about/skill_icons/', verbose_name='تصویر تیره (اختیاری)')),
                ('url', models.URLField(blank=True, null=True, verbose_name='لینک (اختیاری)')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='core.skill', verbose_name='مهارت')),
            ],
            options={
                'verbose_name': 'آیکون مهارت',
                'verbose_name_plural': 'آیکون\u200cهای مهارت',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام شبکه')),
                ('icon', models.ImageField(upload_to='about/social/', verbose_name='آیکون (روشن)')),
                ('icon_dark', models.ImageField(blank=True, null=True, upload_to='about/social/', verbose_name='آیکون (تیره)')),
                ('url', models.URLField(verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.about', verbose_name='درباره')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی',
                'ordering': ['order'],
            },
        ),
    ]
