# Generated by Django 5.2.16 on 2026-08-03 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_about_skill_skillicon_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'اطلاعات شخصی', 'verbose_name_plural': 'اطلاعات شخصی'},
        ),
        migrations.AlterModelOptions(
            name='servicessection',
            options={'verbose_name': 'توانایی', 'verbose_name_plural': 'توانایی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'شبکه اجتماعی', 'verbose_name_plural': 'شبکه\u200cهای اجتماعی'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='circle_text',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='circle_color',
        ),
        migrations.RemoveField(
            model_name='skillicon',
            name='icon_dark',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='icon_dark',
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='about',
            name='quote',
            field=models.CharField(max_length=100, verbose_name='نقل قول'),
        ),
        migrations.AlterField(
            model_name='about',
            name='signature',
            field=models.ImageField(upload_to='about/', verbose_name='امضا'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='bg_color',
            field=models.CharField(max_length=20, verbose_name='رنگ پس زمینه'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.PositiveIntegerField(verbose_name='درصد تسلط(0 تا 100)'),
        ),
        migrations.AlterField(
            model_name='skillicon',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='core.skill', verbose_name='توانایی'),
        ),
        migrations.AlterField(
            model_name='skillicon',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک(اختیاری)'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.ImageField(upload_to='about/social/'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(verbose_name='لینک شبکه اجتماعی'),
        ),
    ]
