# Generated by Django 5.2.16 on 2026-08-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_herosection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='موقعیت(شغلی/تحصیلی)')),
                ('company', models.CharField(max_length=100, verbose_name='نام شرکت/موسسه')),
                ('start_year', models.IntegerField(verbose_name='سال شروع فعالیت')),
                ('end_year', models.CharField(blank=True, max_length=10, null=True, verbose_name='سال اتمام فعالیت/الان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'سابقه کاری',
                'verbose_name_plural': 'سوابق کاری',
            },
        ),
    ]
