# Generated by Django 5.2.16 on 2026-08-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, verbose_name='مدرک تحصیلی')),
                ('university', models.CharField(max_length=100, verbose_name='نام دانشگاه')),
                ('start_year', models.IntegerField(verbose_name='سال شروع تحصیل')),
                ('end_year', models.IntegerField(verbose_name='سال پایان تحصیل')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'سابقه تحصیلی',
                'verbose_name_plural': 'سوابق تحصیلی',
            },
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(max_length=100, verbose_name='کمپانی'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='سال پایان همکاری/الان'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=100, verbose_name='جایگاه شغلی'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_year',
            field=models.IntegerField(verbose_name='سال شروع همکاری'),
        ),
    ]
