# Generated by Django 5.2.16 on 2026-08-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_educationexperience_alter_workexperience_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('وب', 'وب'), ('گرافیک', 'گرافیک'), ('قالب', 'قالب')], max_length=50, verbose_name='دسته بندی')),
                ('thumbnail_picture', models.ImageField(upload_to='portfolio/thumbnail/', verbose_name='تصویر')),
                ('main_picture', models.ImageField(upload_to='portfolio/main/', verbose_name='تصویر اصلی')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک نمونه کار')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها',
            },
        ),
    ]
