# Generated by Django 5.2.16 on 2026-08-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_portfolioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ (برای فیلتر)')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='category',
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='thumbnail_picture',
            field=models.ImageField(upload_to='portfolio/thumbnail/', verbose_name='تصویر بندانگشتی'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='categories',
            field=models.ManyToManyField(related_name='portfolio_items', to='core.portfoliocategory', verbose_name='دسته\u200cبندی\u200cها'),
        ),
    ]
