# Generated by Django 5.2.16 on 2026-08-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_portfoliocategory_remove_portfolioitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicessection',
            name='bg_color',
            field=models.CharField(default='#9d4edd', max_length=20, verbose_name='رنگ پس زمینه'),
        ),
    ]
