# Generated by Django 5.2.16 on 2026-08-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_servicessection_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicessection',
            name='bg_color',
            field=models.CharField(default='#84a59d', max_length=20, verbose_name='رنگ پس زمینه'),
        ),
    ]
