# Generated by Django 5.2.16 on 2026-08-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_servicessection_bg_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('rate_type', models.CharField(choices=[('fixed', 'نرخ ثابت'), ('hourly', 'نرخ ساعتی')], default='fixed', max_length=10, verbose_name='نوع نرخ')),
                ('special_offer', models.CharField(blank=True, max_length=255, null=True, verbose_name='پیشنهاد ویژه')),
                ('proposal', models.TextField(verbose_name='متن پیشنهاد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'درخواست فریلنسری',
                'verbose_name_plural': 'درخواست\u200cهای فریلنسری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('job_type', models.CharField(choices=[('remote', 'شغل مجازی'), ('office', 'شغل اداری')], default='remote', max_length=10, verbose_name='نوع شغل')),
                ('special_offer', models.CharField(blank=True, max_length=255, null=True, verbose_name='حقوق پیشنهادی')),
                ('proposal', models.TextField(verbose_name='متن پیشنهاد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'درخواست شغلی',
                'verbose_name_plural': 'درخواست\u200cهای شغلی',
                'ordering': ['-created_at'],
            },
        ),
    ]
