# Generated by Django 5.2.16 on 2026-08-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_freelancerequest_jobrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('rhetorical_question', models.CharField(max_length=150, verbose_name='سوال غیرمستقیم')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('background_image', models.ImageField(upload_to='hire/')),
            ],
            options={
                'verbose_name': 'همکاری',
                'verbose_name_plural': 'همکاری',
            },
        ),
    ]
