# Generated by Django 5.2.16 on 2026-08-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_hire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('customer_name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('customer_area_activity', models.CharField(max_length=50, verbose_name='حوزه فعالیت مشتری')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='عکس مشتری')),
            ],
        ),
        migrations.AlterField(
            model_name='freelancerequest',
            name='rate_type',
            field=models.CharField(choices=[('hourly', 'نرخ ساعتی'), ('fixed', 'نرخ ثابت')], default='fixed', max_length=10, verbose_name='نوع نرخ'),
        ),
    ]
