# Generated by Django 5.2.16 on 2026-08-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_testimonials_alter_freelancerequest_rate_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'نظر مشتری', 'verbose_name_plural': 'نظرات مشتریان'},
        ),
    ]
