# Generated by Django 5.2.16 on 2026-08-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_testimonials_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='title',
            field=models.CharField(default='پژواک\u200cهای درخشندگی', max_length=50, verbose_name='عنوان'),
        ),
    ]
