# Generated by Django 5.2.16 on 2026-08-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_freelancerequest_rate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='پست\u200cهای بلاگ', max_length=50, verbose_name='عنوان')),
                ('topic', models.CharField(max_length=50, verbose_name='موضوع پست')),
                ('post_title', models.CharField(max_length=255, verbose_name='عنوان پست')),
                ('description', models.TextField(verbose_name='متن پست')),
                ('post_photo', models.ImageField(upload_to='blog/', verbose_name='عکس پست')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
            },
        ),
    ]
