# Generated by Django 5.2.16 on 2026-08-30 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='category_title',
            field=models.CharField(choices=[('آخرین مطالب', 'آخرین مطالب'), ('وبلاگ', 'وبلاگ'), ('مجله', 'مجله'), ('مقالات', 'مقالات')], default='آخرین مطالب', max_length=50, verbose_name='عنوان بخش وبلاگ'),
        ),
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freelancerequest',
            name='rate_type',
            field=models.CharField(choices=[('hourly', 'نرخ ساعتی'), ('fixed', 'نرخ ثابت')], default='fixed', max_length=10, verbose_name='نوع نرخ'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='title',
            field=models.CharField(choices=[('پژواک\u200cهای درخشندگی', 'پژواک\u200cهای درخشندگی'), ('نظرات مشتریان', 'نظرات مشتریان'), ('تجربه\u200cهای همکاری', 'تجربه\u200cهای همکاری'), ('چرا ما؟', 'چرا ما؟')], default='پژواک\u200cهای درخشندگی', max_length=50, verbose_name='عنوان بخش'),
        ),
    ]
