# Generated by Django 5.2.16 on 2026-08-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_blog_title_blog_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='freelancerequest',
            name='rate_type',
            field=models.CharField(choices=[('fixed', 'نرخ ثابت'), ('hourly', 'نرخ ساعتی')], default='fixed', max_length=10, verbose_name='نوع نرخ'),
        ),
    ]
