# Generated by Django 5.2.16 on 2026-08-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_blog_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام شبکه')),
                ('url', models.URLField(verbose_name='لینک')),
                ('icon_class', models.CharField(max_length=50, verbose_name='کلاس آیکون (مثلاً ri-facebook-line)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='freelancerequest',
            name='rate_type',
            field=models.CharField(choices=[('hourly', 'نرخ ساعتی'), ('fixed', 'نرخ ثابت')], default='fixed', max_length=10, verbose_name='نوع نرخ'),
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ملت وب', max_length=100, verbose_name='نام سایت')),
                ('copyright_text', models.CharField(default='تمامی حقوق محفوظ است.', max_length=255, verbose_name='متن کپی\u200cرایت')),
                ('social_links', models.ManyToManyField(blank=True, to='core.footersociallink', verbose_name='شبکه\u200cهای اجتماعی')),
            ],
            options={
                'verbose_name': 'تنظیمات فوتر',
                'verbose_name_plural': 'تنظیمات فوتر',
            },
        ),
    ]
