# Generated by Django 5.2.16 on 2026-08-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_footersociallink_alter_freelancerequest_rate_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='site_name',
            field=models.CharField(default='parsanova', max_length=100, verbose_name='نام سایت'),
        ),
        migrations.AlterField(
            model_name='freelancerequest',
            name='rate_type',
            field=models.CharField(choices=[('fixed', 'نرخ ثابت'), ('hourly', 'نرخ ساعتی')], default='fixed', max_length=10, verbose_name='نوع نرخ'),
        ),
    ]
