# Generated by Django 5.2.16 on 2026-08-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_footer_site_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footersociallink',
            options={'ordering': ['order'], 'verbose_name': 'شبکه اجتماعی فوتر', 'verbose_name_plural': 'شبکه\u200cهای اجتماعی فوتر'},
        ),
        migrations.AlterField(
            model_name='freelancerequest',
            name='rate_type',
            field=models.CharField(choices=[('hourly', 'نرخ ساعتی'), ('fixed', 'نرخ ثابت')], default='fixed', max_length=10, verbose_name='نوع نرخ'),
        ),
    ]
