# Generated by Django 5.2.16 on 2026-08-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_footersociallink_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footersociallink',
            options={'ordering': ['order'], 'verbose_name': 'شبکه اجتماعی در فوتر', 'verbose_name_plural': 'شبکه\u200cهای اجتماعی در فوتر'},
        ),
        migrations.RemoveField(
            model_name='footersociallink',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='footersociallink',
            name='social_icon',
            field=models.ImageField(blank=True, null=True, upload_to='footer/social_link_icons/', verbose_name='آیکون شبکه'),
        ),
    ]
