# Generated by Django 5.2.16 on 2026-08-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_footersociallink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerequest',
            name='rate_type',
            field=models.CharField(choices=[('fixed', 'نرخ ثابت'), ('hourly', 'نرخ ساعتی')], default='fixed', max_length=10, verbose_name='نوع نرخ'),
        ),
    ]
