# Generated by Django 5.2.16 on 2026-08-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_freelancerequest_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerequest',
            name='rate_type',
            field=models.CharField(choices=[('hourly', 'نرخ ساعتی'), ('fixed', 'نرخ ثابت')], default='fixed', max_length=10, verbose_name='نوع نرخ'),
        ),
    ]
