# Generated by Django 5.2.16 on 2026-09-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_freelancerequest_rate_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='educationexperience',
            options={'ordering': ['start_year'], 'verbose_name': 'سابقه تحصیلی', 'verbose_name_plural': 'سوابق تحصیلی'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['order'], 'verbose_name': 'شبکه اجتماعی', 'verbose_name_plural': 'شبکه\u200cهای اجتماعی'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['start_year'], 'verbose_name': 'سابقه کاری', 'verbose_name_plural': 'سوابق کاری'},
        ),
        migrations.RenameField(
            model_name='jobrequest',
            old_name='special_offer',
            new_name='salary_suggestion',
        ),
        migrations.AlterField(
            model_name='freelancerequest',
            name='rate_type',
            field=models.CharField(choices=[('fixed', 'نرخ ثابت'), ('hourly', 'نرخ ساعتی')], default='fixed', max_length=10, verbose_name='نوع نرخ'),
        ),
        migrations.AlterField(
            model_name='hire',
            name='background_image',
            field=models.ImageField(upload_to='hire/', verbose_name='تصویر پس زمینه'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.ImageField(upload_to='about/social/', verbose_name='آیکون شبکه اجتماعی'),
        ),
    ]
